### PR TITLE
Enhance styling of circles to emphasize missing post boxes

### PR DESCRIPTION
**Pull request by planemad**
Includes a few enhancements to bring the focus of the map to missing boxes.

- Change basemap style to dark to give more focus to overlay data points
- Reduce the size of unserveyed locations when zoomed out to emphasize the collected data
- Sort the surveyed circles to ensure missing boxes are drawn on top of existing ones. 
- Adds a url hash parameter to allow permalinking to a location

_Screen4

### CODE REVIEW

**Comment by russbiggs** [comment]
This has quite a few components in it. Here are my thoughts:

* The dark style is a pretty big departure from our current aesthetic and I don't really find it much easier to see the blue dots compared to the StreetV11 layer.
* I think the scaling you've done for the blue dots does have a better look at the lower zoom levels.
* Raising the removed boxes does help emphasize quite a few that I had not seen before, I like this idea.
* not using the url hash was somewhat intentional. There is a feature request, Permalinks for individual boxes #16, that I quite like that would add individual feature routes for easier sharing. I prefer that to generic lat/lng url hashing.

**Comment by mikelmaron** [comment]
Thanks @planemad !

@russbiggs maybe the light style rather than Streets? That would reduce visual clutter, but not change the look as radically.

On the url hash, I think that might be a more achievable solution than permalink for individual boxes. In order to support permalinks to individual boxes, we'd need to set up another service to query the identifiers and get a location; there's no way to consistently and reliably do that when using vector tiles.

**Comment by planemad** [comment]
> The dark style is a pretty big departure from our current aesthetic and I don't really find it much easier to see the blue dots compared to the StreetV11 layer.

Agree, changing the basemap style should go along with fine tuning the circle colors as well. The existing circle colors of blue and green are also hard to distinguish if they overlap.

In any case here's a comparison of streets, light and dark. Maybe stick to streets for now, and work out improving the overall colors separately?

Screen Shot 2020-08-20 at 10 47 45 AM
Screen Shot 2020-08-20 at 10 48 28 AM
Screen Shot 2020-08-20 at 10 48 04 AM

**Comment by russbiggs** [comment]
@mikelmaron the url hash does seem like a better solution to sharing box location in the near term at least.

I like the light map more than dark but also like the POI detail in the streets style for navigating when walking around. Lets stick with streets for now. @planemad I'm totally open to any adjustments on the circle colors. I chose plain red and green but any thoughts you have that may improve it are welcome! the blue is the "official" USPS blue, for whatever that is worth.

**Comment by mikelmaron** [comment]
we could also customize streets to keep the detail, but make a more muted base map

**Comment by ranatalus** [comment]
I agree that URL hashing is probably going to be a more workable solution for right now--can't really speak to whether or not it's better long term, but it will likely be less upkeep at the very least.

I agree that the minimalist streets views seems a little barren, and hard to find visual markers. A less busy map could be better, but graying out everything might be too far.

**Comment by planemad** [comment]
- Switched back to streets style
- Made the surveyed green color more bright to match the red
- Change unserveyed location to a stroked circle to visually indicate that information is missing. This also allows place labels underneath to be more visible

_Screen4

**Comment by ranatalus** [comment]
That looks great to me!

**Comment by mikelmaron** [comment]
like it!

**Comment by russbiggs** [comment]
With the hollow circle for unsurveyed I wonder if we can change over to filled circle with Postal blue for "present" and some of the color blind safe colors suggested in #28 i.e. removed = #d7191c inoperable = #fdae61, it wouldn't make the "present" boxes that apparent but maybe thats ok?

**Comment by frizatch** [comment]
I hadn't seen this PR before adding issue #28, sorry.

- I love the adjustment to the symbol size of the unsurveyed boxes.
- Keeping the postal service blue seems like a good call for the "Present" ones... and the map will fill in with that color.
- I find the hollow symbology a little busy, but it's an interesting way to try and reduce impact from color saturation
- the un-surveyed lighter blue would work to be less distracting on a light map... even it it's solid?
- Thumbs up to a light basemap... custom streets would be sweet.

**Comment by frizatch** [comment]
(Actually, the hollow symbology is only busy at mid-zoom levels... maybe the symbol size for the un-surveyed ought to be set for smaller at those levels as well ) :grin:

**Comment by planemad** [comment]
Great ideas!

> With the hollow circle for unsurveyed I wonder if we can change over to filled circle with Postal blue for "present" and some of the color blind safe colors suggested in #28

✅ 

> the hollow symbology is only busy at mid-zoom levels... maybe the symbol size for the un-surveyed ought to be set for smaller at those levels as well

✅ 

_Screen4

**Comment by russbiggs** [comment]
@planemad Thank you so much for some great additions!

**Comment by planemad** [comment]
🙇 thank you @russbiggs

**Pull request merged**
